[Unit]
Name = "desktop"
Description = "everything I need to work on Windows"
Requires = [
    "komorebi",
    "komorebi-bar",
    "kanata",
    "layer-indicator",
    "event-listeners",
]

[Service]
Kind = "Oneshot"
Autostart = true
Restart = "Never"

[Service.ExecStart]
Executable = "cmd.exe"
Arguments = [
    "/c",
    "",
]
