[Unit]
Name = "kanata"
Description = "software keyboard remapper"

[Service]
Kind = "Simple"
Restart = "OnFailure"
RestartSec = 2

[Service.ExecStart]
Executable = "$USERPROFILE/.config/kanata/kanata_winIOv2.exe"
Arguments = [
    "-c",
    "$USERPROFILE/.config/kanata/kanata.kbd",
    "--port",
    "9999",
]

[Service.Healthcheck.Process]
DelaySec = 1
