[Unit]
Name = "komorebi"
Description = "tiling window management for Windows"
Requires = [
    "whkd",
]

[Service]
Kind = "Simple"
Restart = "OnFailure"
RestartSec = 2

[Service.ExecStart]
Executable = "komorebic.exe"
Arguments = [
    "start",
    "--config",
    "$USERPROFILE/.config/komorebi/komorebi.json",
]
Environment = [[
    "KOMOREBI_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]

[[Service.ExecStop]]
Executable = "komorebic.exe"
Arguments = ["stop"]

[[Service.ExecStopPost]]
Executable = "komorebic.exe"
Arguments = ["restore-windows"]

[Service.Healthcheck.Command]
Executable = "komorebic.exe"
Arguments = ["state"]
DelaySec = 1
