[Unit]
Name = "komorebi-bar"
Description = "grouping of komorebi bars"
Requires = [
    "komorebi-bar-1",
    "komorebi-bar-2",
]

[Service]
Kind = "Oneshot"
Restart = "Never"

[Service.ExecStart]
Executable = "cmd.exe"
Arguments = [
    "/c",
    "",
]
