<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>EventListeners</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefaultItemExcludes>$(DefaultItemExcludes);EventListeners.Tests/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EventListeners.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.8.0" />
    <PackageReference Include="Interop.UIAutomationClient" Version="10.19041.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
  </ItemGroup>

</Project>
