using System.Globalization;
using System.Text;

namespace KeymapGen;

/// <summary>
/// Emits a flat <c>kanata.kbd</c> file from a <see cref="Keymap"/>.
///
/// Layer model emitted:
/// <list type="bullet">
///   <item>base - typing layer; CAP enters one-shot wm (CAP again locks to wm-toggle)</item>
///   <item>wm — one-shot WM mode (default context)</item>
///   <item>wm-toggle — sticky WM mode (default context)</item>
///   <item>wm-X (one per sub-mode) — one-shot sub-mode (peer-switchable; auto-exits)</item>
///   <item>wm-X-toggle — sticky sub-mode (CAPS exits, peer sub-modes switchable)</item>
/// </list>
///
/// Overlay layers (base-X, wm-X) are emitted by <see cref="EmitOverlayLayers"/>;
/// Phase 1 has no overlays so those are not yet exercised.
/// </summary>
internal static class KanataEmitter
{
    public static string Emit(Keymap k)
    {
        var sb = new StringBuilder();

        EmitHeader(sb);
        EmitDefcfg(sb);
        EmitDefsrc(sb, k);
        EmitVirtualKeys(sb, k);

        EmitBaseDefaultLayer(sb);
        EmitWmLayers(sb, k, overlayName: null, overlayBindings: []);

        foreach (var ov in k.Overlays)
        {
            EmitBaseOverlayLayer(sb, ov.Name);
            EmitWmLayers(sb, k, overlayName: ov.Name, overlayBindings: ov.Bindings);
        }

        EmitSubModeOneShot(sb, k);
        EmitSubModeToggle(sb, k);

        return sb.ToString();
    }

    /// <summary>Emits the <see cref="VirtualKey"/> definitions as a defvirtualkeys block.</summary>
    private static void EmitVirtualKeys(StringBuilder sb, Keymap k)
    {
        if (k.VirtualKeys.Count == 0) return;

        sb.AppendLine("(defvirtualkeys");
        foreach (var vk in k.VirtualKeys)
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"  {vk.Name} {ActionFormatter.Format(vk.Action)}");
        }
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitHeader(StringBuilder sb)    {
        sb.AppendLine(";; AUTO-GENERATED by keymap-gen. Do not edit by hand.");
        sb.AppendLine(";; Edit keyboard/keymap-gen/Keymap.cs and run keyboard/regen.ps1");
        sb.AppendLine();
    }

    private static void EmitDefcfg(StringBuilder sb)
    {
        sb.AppendLine("(defcfg");
        sb.AppendLine("  process-unmapped-keys yes");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitDefsrc(StringBuilder sb, Keymap k)
    {
        // defsrc lists keys kanata intercepts. We need caps (the WM-mode trigger)
        // plus every key bound in wm-base, every sub-mode, and every overlay so
        // those layers can actually capture them. Sub-mode layers use ___ XX to
        // deadkey unmapped keys, but that only applies to keys actually in defsrc.
        //
        // lsft/rsft are included so wm-* layers can pass shift through (mapped
        // to themselves) instead of deadkey'ing it via ___ XX. Without this,
        // CAP + Shift + symbol (e.g. CAP + : for psmux command mode) loses the
        // shift event entirely.
        //
        // esc is included so wm-* layers can bind it to "exit to base"; in
        // base-* layers it's not bound (so process-unmapped-keys passes it
        // through normally).
        var keys = new List<string> { "caps", "lsft", "rsft", "esc" };
        foreach (var b in k.WmBase.Bindings) Add(b.Key);
        foreach (var sm in k.SubModes)
            foreach (var b in sm.Bindings) Add(b.Key);
        foreach (var ov in k.Overlays)
            foreach (var b in ov.Bindings) Add(b.Key);

        sb.AppendLine("(defsrc");
        sb.Append("  ");
        sb.AppendLine(string.Join(' ', keys));
        sb.AppendLine(")");
        sb.AppendLine();

        void Add(string key)
        {
            if (!keys.Contains(key, StringComparer.Ordinal)) keys.Add(key);
        }
    }

    private static void EmitBaseDefaultLayer(StringBuilder sb)
    {
        sb.AppendLine(";; base-default: typing layer (default focus context). CAP enters one-shot WM mode.");
        sb.AppendLine("(deflayermap (base-default)");
        // CAP enters one-shot WM mode (a plain layer-switch). Inside WM, CAP
        // toggles one-shot <-> sticky; ESC or completing an action returns here.
        // No tap-dance and no one-shot primitive: locking is just a CAP re-press
        // with no timing window, and the CAP+Shift psmux chord survives because
        // Shift never ends a one-shot (there is no one-shot primitive to end).
        sb.AppendLine("  caps (layer-switch wm)");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitBaseOverlayLayer(StringBuilder sb, string overlayName)
    {
        sb.AppendLine(CultureInfo.InvariantCulture, $";; base-{overlayName}: typing layer ({overlayName} focus context). CAP enters one-shot wm-{overlayName}.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (base-{overlayName})");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  caps (layer-switch wm-{overlayName})");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    /// <summary>
    /// Wrap a one-shot-layer action so it fires and then returns to the typing
    /// layer (<paramref name="exitTarget"/>). This is the "manual one-shot": the
    /// WM layer is entered via a plain layer-switch and each action key exits
    /// after one use, instead of kanata's one-shot primitive (whose re-press
    /// semantics conflict with CAP-to-lock and whose press-variant breaks the
    /// CAP+Shift chord).
    /// </summary>
    private static string FormatWithExit(KAction action, string exitTarget) =>
        $"(multi {ActionFormatter.Format(action)} (layer-switch {exitTarget}))";

    /// <summary>
    /// Emits the WM layers for a given context.
    /// If <paramref name="overlayName"/> is null, emits the default layers
    /// (named <c>wm</c> and <c>wm-toggle</c>) with no overlay bindings.
    /// Otherwise emits <c>wm-{overlayName}</c> and <c>wm-{overlayName}-toggle</c>
    /// with <paramref name="overlayBindings"/> merged on top of wm-base.
    /// </summary>
    private static void EmitWmLayers(StringBuilder sb, Keymap k, string? overlayName, IReadOnlyList<Binding> overlayBindings)
    {
        var suffix = overlayName is null ? string.Empty : $"-{overlayName}";
        var contextLabel = overlayName is null ? "default context" : $"{overlayName} context";
        var overlayKeys = overlayBindings.Select(b => b.Key).ToHashSet();
        // Both one-shot and toggle WM variants for a given context exit to the
        // same base layer. The toggle uses caps; both bind esc as a "panic
        // button" exit available from any WM layer.
        var exitTarget = overlayName is null ? "base-default" : $"base-{overlayName}";

        // One-shot variant: a single CAP lands here. CAP again locks into the
        // sticky variant; ESC or completing one action returns to typing. The
        // "one action then exit" is manual -- every wm-base/overlay action is
        // wrapped (see FormatWithExit) to layer-switch back to the typing layer
        // after firing. Sub-mode entries switch to the one-shot sub-mode layers.
        sb.AppendLine(CultureInfo.InvariantCulture, $";; wm{suffix}: one-shot WM mode ({contextLabel}; first CAP). CAP again locks to sticky.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (wm{suffix})");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  caps (layer-switch wm{suffix}-toggle)");
        foreach (var sm in k.SubModes)
        {
            if (overlayKeys.Contains(sm.EntryKey)) continue; // overlay overrides sub-mode entry
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"  {sm.EntryKey} (layer-switch wm-{sm.Name})");
        }
        foreach (var b in k.WmBase.Bindings)
        {
            if (overlayKeys.Contains(b.Key)) continue; // overlay overrides wm-base
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {FormatWithExit(b.Action, exitTarget)}");
        }
        foreach (var b in overlayBindings)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {FormatWithExit(b.Action, exitTarget)}");
        }
        EmitEscExit(sb, exitTarget);
        EmitShiftPassthrough(sb);
        sb.AppendLine("  ___ XX");
        sb.AppendLine(")");
        sb.AppendLine();

        // Toggle variant: sticky WM mode. CAP returns to the one-shot variant
        // (never directly to typing); ESC exits to the typing layer. Actions are
        // NOT wrapped, so they stay in WM mode for repeated use.
        sb.AppendLine(CultureInfo.InvariantCulture, $";; wm{suffix}-toggle: sticky WM mode ({contextLabel}; CAP again from one-shot).");
        sb.AppendLine(CultureInfo.InvariantCulture, $";; CAP returns to one-shot wm{suffix}; ESC exits to {exitTarget}.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (wm{suffix}-toggle)");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  caps (layer-switch wm{suffix})");
        foreach (var sm in k.SubModes)
        {
            if (overlayKeys.Contains(sm.EntryKey)) continue;
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"  {sm.EntryKey} (layer-switch wm-{sm.Name}-toggle)");
        }
        foreach (var b in k.WmBase.Bindings)
        {
            if (overlayKeys.Contains(b.Key)) continue;
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
        }
        foreach (var b in overlayBindings)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
        }
        EmitEscExit(sb, exitTarget);
        EmitShiftPassthrough(sb);
        sb.AppendLine("  ___ XX");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    /// <summary>
    /// Map lsft/rsft to themselves so Shift passes through to the OS while a
    /// wm-* layer is active. Without this, ___ XX deadkeys Shift and the user
    /// loses shifted symbols like CAP + : (Shift + ;) for psmux command mode.
    /// </summary>
    private static void EmitShiftPassthrough(StringBuilder sb)
    {
        sb.AppendLine("  lsft lsft");
        sb.AppendLine("  rsft rsft");
    }

    /// <summary>
    /// Bind ESC inside a wm-* layer to switch back to <paramref name="exitTarget"/>.
    /// For overlay-specific WM layers, <paramref name="exitTarget"/> is the
    /// overlay's base; for sub-mode layers (which are shared across overlay
    /// contexts), <paramref name="exitTarget"/> is base-default and the bridge
    /// restores the correct overlay via deferred-restore.
    /// </summary>
    private static void EmitEscExit(StringBuilder sb, string exitTarget)
    {
        sb.AppendLine(CultureInfo.InvariantCulture, $"  esc (layer-switch {exitTarget})");
    }

    private static void EmitSubModeOneShot(StringBuilder sb, Keymap k)
    {
        foreach (var sm in k.SubModes)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $";; wm-{sm.Name}: one-shot sub-mode (each action returns to typing; peer sub-modes switchable)");
            sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (wm-{sm.Name})");
            // Peer sub-mode entries switch to the peer's ONE-SHOT layer, so a
            // wrong-mode press hops between sub-modes while keeping one-shot
            // semantics: the next action still fires and returns to typing.
            foreach (var peer in k.SubModes)
            {
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"  {peer.EntryKey} (layer-switch wm-{peer.Name})");
            }
            foreach (var b in sm.Bindings)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {FormatWithExit(b.Action, "base-default")}");
            }
            EmitEscExit(sb, "base-default");
            sb.AppendLine("  ___ XX");
            sb.AppendLine(")");
            sb.AppendLine();
        }
    }

    private static void EmitSubModeToggle(StringBuilder sb, Keymap k)
    {
        foreach (var sm in k.SubModes)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $";; wm-{sm.Name}-toggle: sticky sub-mode (CAPS/ESC exit, peer sub-modes switchable)");
            sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (wm-{sm.Name}-toggle)");
            sb.AppendLine("  caps (layer-switch base-default)");
            // peer sub-mode entries
            foreach (var peer in k.SubModes)
            {
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"  {peer.EntryKey} (layer-switch wm-{peer.Name}-toggle)");
            }
            // sub-mode-specific bindings (these override peer entries if conflicts; e.g. wm-move-toggle's 1-8 override workspaces->move-to)
            foreach (var b in sm.Bindings)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
            }
            // shared actions from wm-base (excluding sub-mode entries that are already laid out above)
            var subModeEntryKeys = k.SubModes.Select(s => s.EntryKey).ToHashSet();
            var subModeBindingKeys = sm.Bindings.Select(b => b.Key).ToHashSet();
            foreach (var b in k.WmBase.Bindings)
            {
                if (subModeEntryKeys.Contains(b.Key)) continue;       // entries already emitted
                if (subModeBindingKeys.Contains(b.Key)) continue;     // sub-mode override wins
                sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
            }
            EmitEscExit(sb, "base-default");
            sb.AppendLine("  ___ XX");
            sb.AppendLine(")");
            sb.AppendLine();
        }
    }
}
