using System.Globalization;
using System.Text;

namespace KeymapGen;

/// <summary>
/// Emits a flat <c>kanata.kbd</c> file from a <see cref="Keymap"/>.
///
/// Layer model emitted:
/// <list type="bullet">
///   <item>base - typing layer; CAP enters one-shot wm (CAP again locks to wm-toggle)</item>
///   <item>wm — one-shot WM mode (default context)</item>
///   <item>wm-toggle — sticky WM mode (default context)</item>
///   <item>wm-X (one per sub-mode) — one-shot sub-mode (peer-switchable; auto-exits)</item>
///   <item>wm-X-toggle — sticky sub-mode (CAPS exits, peer sub-modes switchable)</item>
/// </list>
///
/// Overlay layers (base-X, wm-X) are emitted by <see cref="EmitOverlayLayers"/>;
/// Phase 1 has no overlays so those are not yet exercised.
/// </summary>
internal static class KanataEmitter
{
    private const string ShortcutModifiers = "lctl rctl lalt ralt lmet rmet";
    private const string ClickBlockingModifiers =
        "lsft rsft rctl lalt ralt lmet rmet";
    private static readonly string[] ModifierPassthroughKeys =
        ["lsft", "rsft", "lctl", "rctl", "lalt", "ralt", "lmet", "rmet"];
    private static readonly string[] PointerKeyboardKeys =
    [
        "grv", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "-", "=", "bspc",
        "tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]", "\\",
        "caps", "a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "'", "ret",
        "lsft", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/", "rsft",
        "lctl", "lmet", "lalt", "spc", "ralt", "rmet", "rctl",
        "up", "down", "left", "right", "home", "end", "pgup", "pgdn", "ins", "del",
        "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12",
    ];
    private static readonly HashSet<string> PointerPassthroughKeys =
    [
        "tab", "ret", "bspc", "up", "down", "left", "right", "home", "end",
        "pgup", "pgdn", "ins", "del", "f1", "f2", "f3", "f4", "f5", "f6",
        "f7", "f8", "f9", "f10", "f11", "f12",
    ];

    public static string Emit(Keymap k)
    {
        var sb = new StringBuilder();

        EmitHeader(sb);
        EmitDefcfg(sb, k);
        EmitDefsrc(sb, k);
        EmitVirtualKeys(sb, k);

        EmitBaseDefaultLayer(sb);
        EmitWmLayers(sb, k, overlayName: null, overlayBindings: []);

        foreach (var ov in k.Overlays)
        {
            EmitBaseOverlayLayer(sb, ov.Name);
            EmitWmLayers(sb, k, overlayName: ov.Name, overlayBindings: ov.Bindings);
        }

        if (k.PointerMode is not null)
        {
            EmitPointerLayer(sb, k, overlayName: null);
            EmitPointerDepartureLayers(
                sb,
                overlayName: null,
                k.PointerMode.HintProvider);
            foreach (var ov in k.Overlays)
            {
                EmitPointerLayer(sb, k, ov.Name);
                EmitPointerDepartureLayers(
                    sb,
                    ov.Name,
                    k.PointerMode.HintProvider);
            }
        }

        EmitSubModeOneShot(sb, k);
        EmitSubModeToggle(sb, k);

        return sb.ToString();
    }

    /// <summary>Emits the <see cref="VirtualKey"/> definitions as a defvirtualkeys block.</summary>
    private static void EmitVirtualKeys(StringBuilder sb, Keymap k)
    {
        if (k.VirtualKeys.Count == 0) return;

        sb.AppendLine("(defvirtualkeys");
        foreach (var vk in k.VirtualKeys)
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"  {vk.Name} {ActionFormatter.Format(vk.Action)}");
        }
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitHeader(StringBuilder sb)    {
        sb.AppendLine(";; AUTO-GENERATED by keymap-gen. Do not edit by hand.");
        sb.AppendLine(";; Edit keyboard/keymap-gen/Keymap.cs and run keyboard/regen.ps1");
        sb.AppendLine();
    }

    private static void EmitDefcfg(StringBuilder sb, Keymap k)
    {
        sb.AppendLine("(defcfg");
        sb.AppendLine("  process-unmapped-keys yes");
        if (k.PointerMode is not null)
        {
            sb.AppendLine("  movemouse-inherit-accel-state yes");
            sb.AppendLine("  movemouse-smooth-diagonals yes");
        }
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitDefsrc(StringBuilder sb, Keymap k)
    {
        // defsrc lists keys kanata intercepts. We need caps (the WM-mode trigger)
        // plus every key bound in wm-base, every sub-mode, and every overlay so
        // those layers can actually capture them. Sub-mode layers use ___ XX to
        // deadkey unmapped keys, but that only applies to keys actually in defsrc.
        //
        // lsft/rsft are included so wm-* layers can pass shift through (mapped
        // to themselves) instead of deadkey'ing it via ___ XX. Without this,
        // CAP + Shift + symbol (e.g. CAP + : for psmux command mode) loses the
        // shift event entirely.
        //
        // esc is included so wm-* layers can bind it to "exit to base"; in
        // base-* layers it's not bound (so process-unmapped-keys passes it
        // through normally).
        var keys = CollectDefsrcKeys(k);

        sb.AppendLine("(defsrc");
        sb.Append("  ");
        sb.AppendLine(string.Join(' ', keys));
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static List<string> CollectDefsrcKeys(Keymap k)
    {
        var keys = new List<string> { "caps", "esc" };
        keys.AddRange(ModifierPassthroughKeys);
        foreach (var b in k.WmBase.Bindings) Add(b.Key);
        foreach (var sm in k.SubModes)
            foreach (var b in sm.Bindings) Add(b.Key);
        foreach (var ov in k.Overlays)
            foreach (var b in ov.Bindings) Add(b.Key);
        if (k.PointerMode is not null)
        {
            foreach (var key in PointerKeyboardKeys) Add(key);
        }

        void Add(string key)
        {
            if (!keys.Contains(key, StringComparer.Ordinal)) keys.Add(key);
        }

        return keys;
    }

    private static void EmitBaseDefaultLayer(StringBuilder sb)
    {
        sb.AppendLine(";; base-default: typing layer (default focus context). CAP enters one-shot WM mode.");
        sb.AppendLine("(deflayermap (base-default)");
        // CAP enters one-shot WM mode (a plain layer-switch). Inside WM, CAP
        // toggles one-shot <-> sticky; ESC or completing an action returns here.
        // No tap-dance and no one-shot primitive: locking is just a CAP re-press
        // with no timing window, and the CAP+Shift psmux chord survives because
        // Shift never ends a one-shot (there is no one-shot primitive to end).
        sb.AppendLine("  caps (layer-switch wm)");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitBaseOverlayLayer(StringBuilder sb, string overlayName)
    {
        sb.AppendLine(CultureInfo.InvariantCulture, $";; base-{overlayName}: typing layer ({overlayName} focus context). CAP enters one-shot wm-{overlayName}.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (base-{overlayName})");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  caps (layer-switch wm-{overlayName})");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    /// <summary>
    /// Wrap a one-shot-layer action so it fires and then returns to the typing
    /// layer (<paramref name="exitTarget"/>). This is the "manual one-shot": the
    /// WM layer is entered via a plain layer-switch and each action key exits
    /// after one use, instead of kanata's one-shot primitive (whose re-press
    /// semantics conflict with CAP-to-lock and whose press-variant breaks the
    /// CAP+Shift chord).
    /// </summary>
    private static string FormatWithExit(KAction action, string exitTarget) =>
        $"(multi {ActionFormatter.Format(action)} (layer-switch {exitTarget}))";

    /// <summary>
    /// Emits the WM layers for a given context.
    /// If <paramref name="overlayName"/> is null, emits the default layers
    /// (named <c>wm</c> and <c>wm-toggle</c>) with no overlay bindings.
    /// Otherwise emits <c>wm-{overlayName}</c> and <c>wm-{overlayName}-toggle</c>
    /// with <paramref name="overlayBindings"/> merged on top of wm-base.
    /// </summary>
    private static void EmitWmLayers(StringBuilder sb, Keymap k, string? overlayName, IReadOnlyList<Binding> overlayBindings)
    {
        var suffix = overlayName is null ? string.Empty : $"-{overlayName}";
        var contextLabel = overlayName is null ? "default context" : $"{overlayName} context";
        var overlayKeys = overlayBindings.Select(b => b.Key).ToHashSet();
        // Both one-shot and toggle WM variants for a given context exit to the
        // same base layer. The toggle uses caps; both bind esc as a "panic
        // button" exit available from any WM layer.
        var exitTarget = overlayName is null ? "base-default" : $"base-{overlayName}";
        var pointerLayer = overlayName is null ? "pointer" : $"pointer-{overlayName}";

        // One-shot variant: a single CAP lands here. CAP again locks into the
        // sticky variant; ESC or completing one action returns to typing. The
        // "one action then exit" is manual -- every wm-base/overlay action is
        // wrapped (see FormatWithExit) to layer-switch back to the typing layer
        // after firing. Sub-mode entries switch to the one-shot sub-mode layers.
        sb.AppendLine(CultureInfo.InvariantCulture, $";; wm{suffix}: one-shot WM mode ({contextLabel}; first CAP). CAP again locks to sticky.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (wm{suffix})");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  caps (layer-switch wm{suffix}-toggle)");
        if (k.PointerMode is { } pointer)
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"  {pointer.EntryKey} (layer-switch {pointerLayer})");
        }
        foreach (var sm in k.SubModes)
        {
            if (overlayKeys.Contains(sm.EntryKey)) continue; // overlay overrides sub-mode entry
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"  {sm.EntryKey} (layer-switch wm-{sm.Name})");
        }
        foreach (var b in k.WmBase.Bindings)
        {
            if (overlayKeys.Contains(b.Key)) continue; // overlay overrides wm-base
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {FormatWithExit(b.Action, exitTarget)}");
        }
        foreach (var b in overlayBindings)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {FormatWithExit(b.Action, exitTarget)}");
        }
        EmitEscExit(sb, exitTarget);
        EmitModifierPassthrough(sb);
        sb.AppendLine("  ___ XX");
        sb.AppendLine(")");
        sb.AppendLine();

        // Toggle variant: sticky WM mode. CAP returns to the one-shot variant
        // (never directly to typing); ESC exits to the typing layer. Actions are
        // NOT wrapped, so they stay in WM mode for repeated use.
        sb.AppendLine(CultureInfo.InvariantCulture, $";; wm{suffix}-toggle: sticky WM mode ({contextLabel}; CAP again from one-shot).");
        sb.AppendLine(CultureInfo.InvariantCulture, $";; CAP returns to one-shot wm{suffix}; ESC exits to {exitTarget}.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (wm{suffix}-toggle)");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  caps (layer-switch wm{suffix})");
        if (k.PointerMode is { } pointerToggle)
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"  {pointerToggle.EntryKey} (layer-switch {pointerLayer})");
        }
        foreach (var sm in k.SubModes)
        {
            if (overlayKeys.Contains(sm.EntryKey)) continue;
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"  {sm.EntryKey} (layer-switch wm-{sm.Name}-toggle)");
        }
        foreach (var b in k.WmBase.Bindings)
        {
            if (overlayKeys.Contains(b.Key)) continue;
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
        }
        foreach (var b in overlayBindings)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
        }
        EmitEscExit(sb, exitTarget);
        EmitModifierPassthrough(sb);
        sb.AppendLine("  ___ XX");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitPointerLayer(
        StringBuilder sb,
        Keymap k,
        string? overlayName)
    {
        var pointer = k.PointerMode
            ?? throw new InvalidOperationException("Pointer mode is not configured.");
        var suffix = overlayName is null ? string.Empty : $"-{overlayName}";
        var layerName = $"pointer{suffix}";
        var exitTarget = overlayName is null
            ? "pointer-exit"
            : $"pointer-exit-{overlayName}";
        var uiHintTarget = overlayName is null
            ? "pointer-hint-ui"
            : $"pointer-hint-ui-{overlayName}";
        var gridHintTarget = overlayName is null
            ? "pointer-hint-grid"
            : $"pointer-hint-grid-{overlayName}";
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $";; {layerName}: persistent Kanata-native pointer mode; Caps/Escape exits through {exitTarget}.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap ({layerName})");
        foreach (var binding in pointer.Bindings)
        {
            var action = ActionFormatter.Format(binding.Action);
            var modifierTriggers = binding.Key is ";" or "'"
                ? ClickBlockingModifiers
                : ShortcutModifiers;
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"  {binding.Key} (fork {action} {binding.Key} ({modifierTriggers}))");
        }
        var hintAction = $"(layer-switch {uiHintTarget})";
        var shiftedHintAction = $"(layer-switch {gridHintTarget})";
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"  {pointer.HintKey} (fork (fork {hintAction} {shiftedHintAction} (lsft rsft)) {pointer.HintKey} ({ShortcutModifiers}))");
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"  caps (layer-switch {exitTarget})");
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"  esc (layer-switch {exitTarget})");
        EmitModifierPassthrough(sb);

        var explicitKeys = pointer.Bindings
            .Select(binding => binding.Key)
            .Append(pointer.HintKey)
            .Append("caps")
            .Append("esc")
            .Concat(ModifierPassthroughKeys)
            .ToHashSet(StringComparer.Ordinal);
        foreach (var key in PointerKeyboardKeys)
        {
            if (explicitKeys.Contains(key)) continue;
            var action = PointerPassthroughKeys.Contains(key)
                ? key
                : $"(fork XX {key} ({ShortcutModifiers}))";
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {key} {action}");
        }
        sb.AppendLine("  ___ XX");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitPointerDepartureLayers(
        StringBuilder sb,
        string? overlayName,
        PointerHintProvider hintProvider)
    {
        var suffix = overlayName is null ? string.Empty : $"-{overlayName}";
        var wmTarget = overlayName is null ? "wm" : $"wm-{overlayName}";
        var exitLayer = $"pointer-exit{suffix}";
        EmitPointerFallbackLayer(sb, exitLayer, wmTarget);
        if (hintProvider is PointerHintProvider.PointerUi)
        {
            EmitPointerInputLayer(
                sb,
                $"pointer-hint-ui{suffix}",
                exitLayer);
            EmitPointerInputLayer(
                sb,
                $"pointer-hint-grid{suffix}",
                exitLayer);
        }
        else
        {
            EmitPointerFallbackLayer(
                sb,
                $"pointer-hint-ui{suffix}",
                wmTarget);
            EmitPointerFallbackLayer(
                sb,
                $"pointer-hint-grid{suffix}",
                wmTarget);
        }
    }

    private static void EmitPointerFallbackLayer(
        StringBuilder sb,
        string layerName,
        string wmTarget)
    {
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $";; {layerName}: typing fallback while the bridge restores the latest base context.");
        sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap ({layerName})");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  caps (layer-switch {wmTarget})");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitPointerInputLayer(
        StringBuilder sb,
        string layerName,
        string exitLayer)
    {
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $";; {layerName}: provider-owned hint input.");
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"(deflayermap ({layerName})");
        foreach (var key in "asdfghjklqwertyuiopzxcvbnm")
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"  {key} (push-msg \"pointer.hint.key.{char.ToUpperInvariant(key)}\")");
        }
        sb.AppendLine(
            "  bspc (push-msg \"pointer.hint.backspace\")");
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"  esc (multi (push-msg \"pointer.hint.cancel\") (layer-switch {exitLayer}))");
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"  caps (multi (push-msg \"pointer.hint.cancel\") (layer-switch {exitLayer}))");
        EmitModifierPassthrough(sb);
        sb.AppendLine("  ___ XX");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    /// <summary>
    /// Map modifiers to themselves so shortcuts pass through while a modal
    /// layer is active. Without this, ___ XX deadkeys the modifier and breaks
    /// chords such as Alt+Tab, Ctrl+C, or CAP + : (Shift + ;).
    /// </summary>
    private static void EmitModifierPassthrough(StringBuilder sb)
    {
        foreach (var key in ModifierPassthroughKeys)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {key} {key}");
        }
    }

    /// <summary>
    /// Bind ESC inside a wm-* layer to switch back to <paramref name="exitTarget"/>.
    /// For overlay-specific WM layers, <paramref name="exitTarget"/> is the
    /// overlay's base; for sub-mode layers (which are shared across overlay
    /// contexts), <paramref name="exitTarget"/> is base-default and the bridge
    /// restores the correct overlay via deferred-restore.
    /// </summary>
    private static void EmitEscExit(StringBuilder sb, string exitTarget)
    {
        sb.AppendLine(CultureInfo.InvariantCulture, $"  esc (layer-switch {exitTarget})");
    }

    private static void EmitSubModeOneShot(StringBuilder sb, Keymap k)
    {
        foreach (var sm in k.SubModes)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $";; wm-{sm.Name}: one-shot sub-mode (each action returns to typing; peer sub-modes switchable)");
            sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (wm-{sm.Name})");
            // Peer sub-mode entries switch to the peer's ONE-SHOT layer, so a
            // wrong-mode press hops between sub-modes while keeping one-shot
            // semantics: the next action still fires and returns to typing.
            foreach (var peer in k.SubModes)
            {
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"  {peer.EntryKey} (layer-switch wm-{peer.Name})");
            }
            if (k.PointerMode is { } pointer)
            {
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"  {pointer.EntryKey} (layer-switch pointer)");
            }
            foreach (var b in sm.Bindings)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {FormatWithExit(b.Action, "base-default")}");
            }
            EmitEscExit(sb, "base-default");
            EmitModifierPassthrough(sb);
            sb.AppendLine("  ___ XX");
            sb.AppendLine(")");
            sb.AppendLine();
        }
    }

    private static void EmitSubModeToggle(StringBuilder sb, Keymap k)
    {
        foreach (var sm in k.SubModes)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $";; wm-{sm.Name}-toggle: sticky sub-mode (CAPS/ESC exit, peer sub-modes switchable)");
            sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (wm-{sm.Name}-toggle)");
            sb.AppendLine("  caps (layer-switch base-default)");
            // peer sub-mode entries
            foreach (var peer in k.SubModes)
            {
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"  {peer.EntryKey} (layer-switch wm-{peer.Name}-toggle)");
            }
            if (k.PointerMode is { } pointer)
            {
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"  {pointer.EntryKey} (layer-switch pointer)");
            }
            // sub-mode-specific bindings (these override peer entries if conflicts; e.g. wm-move-toggle's 1-8 override workspaces->move-to)
            foreach (var b in sm.Bindings)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
            }
            // shared actions from wm-base (excluding sub-mode entries that are already laid out above)
            var subModeEntryKeys = k.SubModes.Select(s => s.EntryKey).ToHashSet();
            var subModeBindingKeys = sm.Bindings.Select(b => b.Key).ToHashSet();
            foreach (var b in k.WmBase.Bindings)
            {
                if (subModeEntryKeys.Contains(b.Key)) continue;       // entries already emitted
                if (subModeBindingKeys.Contains(b.Key)) continue;     // sub-mode override wins
                sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
            }
            EmitEscExit(sb, "base-default");
            EmitModifierPassthrough(sb);
            sb.AppendLine("  ___ XX");
            sb.AppendLine(")");
            sb.AppendLine();
        }
    }
}
