using System.Globalization;
using System.Text;

namespace KeymapGen;

/// <summary>
/// Emits a flat <c>kanata.kbd</c> file from a <see cref="Keymap"/>.
///
/// Layer model emitted:
/// <list type="bullet">
///   <item>base — typing layer with CapsLock tap-dance into wm/wm-toggle</item>
///   <item>wm — one-shot WM mode (default context)</item>
///   <item>wm-toggle — sticky WM mode (default context)</item>
///   <item>wm-X (one per sub-mode) — one-shot sub-mode (auto-exits)</item>
///   <item>wm-X-toggle — sticky sub-mode (CAPS exits, peer sub-modes switchable)</item>
/// </list>
///
/// Overlay layers (base-X, wm-X) are emitted by <see cref="EmitOverlayLayers"/>;
/// Phase 1 has no overlays so those are not yet exercised.
/// </summary>
internal static class KanataEmitter
{
    public static string Emit(Keymap k)
    {
        var sb = new StringBuilder();

        EmitHeader(sb);
        EmitDefcfg(sb);
        EmitDefsrc(sb, k);
        EmitDefvar(sb, k);

        EmitBaseLayer(sb, k);
        EmitWmLayers(sb, k);
        EmitSubModeOneShot(sb, k);
        EmitSubModeToggle(sb, k);

        return sb.ToString();
    }

    private static void EmitHeader(StringBuilder sb)
    {
        sb.AppendLine(";; AUTO-GENERATED by keymap-gen. Do not edit by hand.");
        sb.AppendLine(";; Edit keyboard/keymap-gen/Keymap.cs and run keyboard/regen.ps1");
        sb.AppendLine();
    }

    private static void EmitDefcfg(StringBuilder sb)
    {
        sb.AppendLine("(defcfg");
        sb.AppendLine("  process-unmapped-keys yes");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitDefsrc(StringBuilder sb, Keymap k)
    {
        // defsrc lists keys kanata intercepts. We need caps (the WM-mode trigger)
        // plus every key bound in the wm-base layer so the WM layer can capture
        // them. Sub-mode layers use ___ XX to deadkey unmapped keys, but that
        // only applies to keys actually in defsrc.
        var keys = new List<string> { "caps" };
        foreach (var b in k.WmBase.Bindings)
        {
            if (!keys.Contains(b.Key, StringComparer.Ordinal))
                keys.Add(b.Key);
        }
        sb.AppendLine("(defsrc");
        sb.Append("  ");
        sb.AppendLine(string.Join(' ', keys));
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitDefvar(StringBuilder sb, Keymap k)
    {
        sb.AppendLine("(defvar");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  os-timeout {k.Caps.OneShotTimeoutMs}");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  td-timeout {k.Caps.TapDanceTimeoutMs}");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitBaseLayer(StringBuilder sb, Keymap k)
    {
        sb.AppendLine(";; base: typing layer. CAP tap-dances into WM mode.");
        sb.AppendLine("(deflayermap (base)");
        sb.AppendLine("  caps (tap-dance $td-timeout (");
        sb.AppendLine("    (one-shot $os-timeout (layer-while-held wm))");
        sb.AppendLine("    (layer-switch wm-toggle)");
        sb.AppendLine("  ))");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitWmLayers(StringBuilder sb, Keymap k)
    {
        // wm: one-shot WM mode. Sub-mode entries are one-shot wrappers.
        sb.AppendLine(";; wm: one-shot WM mode (CAP single-tap)");
        sb.AppendLine("(deflayermap (wm)");
        foreach (var sm in k.SubModes)
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"  {sm.EntryKey} (one-shot $os-timeout (layer-while-held wm-{sm.Name}))");
        }
        foreach (var b in k.WmBase.Bindings)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
        }
        sb.AppendLine("  ___ XX");
        sb.AppendLine(")");
        sb.AppendLine();

        // wm-toggle: sticky WM mode. Sub-mode entries layer-switch.
        sb.AppendLine(";; wm-toggle: sticky WM mode (CAP double-tap)");
        sb.AppendLine("(deflayermap (wm-toggle)");
        sb.AppendLine("  caps (layer-switch base)");
        foreach (var sm in k.SubModes)
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"  {sm.EntryKey} (layer-switch wm-{sm.Name}-toggle)");
        }
        foreach (var b in k.WmBase.Bindings)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
        }
        sb.AppendLine("  ___ XX");
        sb.AppendLine(")");
        sb.AppendLine();
    }

    private static void EmitSubModeOneShot(StringBuilder sb, Keymap k)
    {
        foreach (var sm in k.SubModes)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $";; wm-{sm.Name}: one-shot sub-mode (auto-exits after one action)");
            sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (wm-{sm.Name})");
            foreach (var b in sm.Bindings)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
            }
            sb.AppendLine("  ___ XX");
            sb.AppendLine(")");
            sb.AppendLine();
        }
    }

    private static void EmitSubModeToggle(StringBuilder sb, Keymap k)
    {
        foreach (var sm in k.SubModes)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $";; wm-{sm.Name}-toggle: sticky sub-mode (CAPS exits, peer sub-modes switchable)");
            sb.AppendLine(CultureInfo.InvariantCulture, $"(deflayermap (wm-{sm.Name}-toggle)");
            sb.AppendLine("  caps (layer-switch base)");
            // peer sub-mode entries
            foreach (var peer in k.SubModes)
            {
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"  {peer.EntryKey} (layer-switch wm-{peer.Name}-toggle)");
            }
            // sub-mode-specific bindings (these override peer entries if conflicts; e.g. wm-move-toggle's 1-8 override workspaces->move-to)
            foreach (var b in sm.Bindings)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
            }
            // shared actions from wm-base (excluding sub-mode entries that are already laid out above)
            var subModeEntryKeys = k.SubModes.Select(s => s.EntryKey).ToHashSet();
            var subModeBindingKeys = sm.Bindings.Select(b => b.Key).ToHashSet();
            foreach (var b in k.WmBase.Bindings)
            {
                if (subModeEntryKeys.Contains(b.Key)) continue;       // entries already emitted
                if (subModeBindingKeys.Contains(b.Key)) continue;     // sub-mode override wins
                sb.AppendLine(CultureInfo.InvariantCulture, $"  {b.Key} {ActionFormatter.Format(b.Action)}");
            }
            sb.AppendLine("  ___ XX");
            sb.AppendLine(")");
            sb.AppendLine();
        }
    }
}
