using System.Globalization;
using System.Text;

namespace KeymapGen;

/// <summary>
/// Emits <c>KEYMAP.md</c> -- a human-readable cheatsheet derived from the DSL.
/// One source of truth: when bindings change, regen.ps1 produces a fresh cheatsheet.
/// </summary>
internal static class KeymapMdEmitter
{
    public static string Emit(Keymap k)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!-- AUTO-GENERATED by keymap-gen. Do not edit by hand. -->");
        sb.AppendLine("<!-- Edit keyboard/keymap-gen/ProductionKeymap.cs and run keyboard/regen.ps1 -->");
        sb.AppendLine();
        sb.AppendLine("# Keymap reference");
        sb.AppendLine();
        sb.AppendLine("CapsLock is the WM mode trigger:");
        sb.AppendLine();
        sb.AppendLine("- **One CAP** = one-shot WM mode (do one action, then back to typing)");
        sb.AppendLine("- **CAP again** = lock into sticky WM mode");
        sb.AppendLine("- CAP toggles one-shot vs sticky; **ESC** (or finishing a one-shot action) returns to typing");
        sb.AppendLine();

        EmitGlobals(sb, k);
        EmitSubModes(sb, k);
        EmitOverlays(sb, k);

        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("See `keyboard/README.md` for architecture and `keyboard/INTENTS.md` for intent vocabulary.");
        return sb.ToString();
    }

    private static void EmitGlobals(StringBuilder sb, Keymap k)
    {
        sb.AppendLine("## wm-base (truly global)");
        sb.AppendLine();
        sb.AppendLine("Always available inside WM mode regardless of overlay or sub-mode.");
        sb.AppendLine();
        EmitNote(sb, k.WmBase.Note);
        sb.AppendLine("| Key | Action |");
        sb.AppendLine("|---|---|");
        foreach (var b in k.WmBase.Bindings.OrderBy(b => b.Key, StringComparer.Ordinal))
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"| `CAP {b.Key}` | {Describe(b)} |");
        }
        sb.AppendLine();
        sb.AppendLine("### Sub-mode entries");
        sb.AppendLine();
        sb.AppendLine("Press inside WM mode to enter a sub-mode:");
        sb.AppendLine();
        sb.AppendLine("| Key | Sub-mode |");
        sb.AppendLine("|---|---|");
        foreach (var sm in k.SubModes.OrderBy(s => s.EntryKey, StringComparer.Ordinal))
        {
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"| `CAP {sm.EntryKey}` | wm-{sm.Name} |");
        }
        sb.AppendLine();
    }

    private static void EmitSubModes(StringBuilder sb, Keymap k)
    {
        foreach (var sm in k.SubModes)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"## wm-{sm.Name}");
            sb.AppendLine();
            sb.AppendLine(CultureInfo.InvariantCulture, $"Entered via `CAP {sm.EntryKey}`.");
            sb.AppendLine();
            EmitNote(sb, sm.Note);
            sb.AppendLine("| Key | Action |");
            sb.AppendLine("|---|---|");
            foreach (var b in sm.Bindings.OrderBy(b => b.Key, StringComparer.Ordinal))
            {
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"| `CAP {sm.EntryKey} {b.Key}` | {Describe(b)} |");
            }
            sb.AppendLine();
        }
    }

    private static void EmitOverlays(StringBuilder sb, Keymap k)
    {
        if (k.Overlays.Count == 0) return;

        sb.AppendLine("## App overlays");
        sb.AppendLine();
        sb.AppendLine("Active when the bridge's `AppLayerRouter` routes the focused app to this layer.");
        sb.AppendLine();
        foreach (var ov in k.Overlays)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"### wm-{ov.Name}");
            sb.AppendLine();
            EmitNote(sb, ov.Note);
            sb.AppendLine("| Key | Action |");
            sb.AppendLine("|---|---|");
            foreach (var b in ov.Bindings.OrderBy(b => b.Key, StringComparer.Ordinal))
            {
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"| `CAP {b.Key}` | {Describe(b)} |");
            }
            sb.AppendLine();
        }
    }

    private static void EmitNote(StringBuilder sb, string? note)
    {
        if (string.IsNullOrWhiteSpace(note)) return;
        sb.AppendLine(note);
        sb.AppendLine();
    }

    private static string Describe(Binding b)
    {
        var core = DescribeAction(b.Action);
        return b.Description is null ? core : $"{b.Description}: {core}";
    }

    private static string DescribeAction(KAction a) => a switch
    {
        IntentAction i => $"intent `{i.Name}`",
        MacroAction m => "macro " + DescribeMacro(m),
        KanataLiteral l => $"raw kanata: `{l.Lisp}`",
        _ => a.GetType().Name,
    };

    private static string DescribeMacro(MacroAction m)
    {
        var parts = m.Steps.Select(s => s switch
        {
            MacroChord c => $"`{c.Chord}`",
            MacroKey k => $"`{k.Key}`",
            MacroDelay d => $"{d.Ms}ms",
            MacroIntent i => $"intent `{i.Name}`",
            MacroLiteral l => $"`{l.Lisp}`",
            MacroUnmodKey k => $"`{k.Key}`",
            _ => "?",
        });
        return string.Join(" → ", parts);
    }
}
