using System.Globalization;
using System.Text;

namespace KeymapGen;

/// <summary>
/// Emits <c>LayerCatalog.g.cs</c> -- a C# class with string constants for every
/// kanata layer the compiler produces. The bridge references these constants when
/// routing focus changes to layer-switch requests, so a typo breaks the build
/// instead of failing silently at runtime.
/// </summary>
internal static class LayerCatalogEmitter
{
    public static string Emit(Keymap k)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED by keymap-gen. Do not edit by hand.");
        sb.AppendLine("// Edit keyboard/keymap-gen/ProductionKeymap.cs and run keyboard/regen.ps1");
        sb.AppendLine();
        sb.AppendLine("namespace EventListeners.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Names of every kanata layer the compiler emits. Use these constants in");
        sb.AppendLine("/// bridge code (e.g., AppLayerRouter) to avoid stringly-typed references.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class LayerCatalog");
        sb.AppendLine("{");

        // Focus-context base layers (one per overlay, plus 'default')
        sb.AppendLine("    // Focus-context base layers (typing layer; what 'caps' enters WM FROM)");
        sb.AppendLine("    public const string BaseDefault = \"base-default\";");
        foreach (var ov in k.Overlays)
        {
            var prop = "Base" + Pascalize(ov.Name);
            sb.AppendLine(CultureInfo.InvariantCulture, $"    public const string {prop} = \"base-{ov.Name}\";");
        }

        if (k.PointerMode is not null)
        {
            sb.AppendLine();
            sb.AppendLine("    // Persistent pointer layers (one per focus context).");
            sb.AppendLine("    public const string Pointer = \"pointer\";");
            sb.AppendLine("    public const string PointerExit = \"pointer-exit\";");
            sb.AppendLine("    public const string PointerHintUi = \"pointer-hint-ui\";");
            sb.AppendLine("    public const string PointerHintGrid = \"pointer-hint-grid\";");
            foreach (var ov in k.Overlays)
            {
                var prop = "Pointer" + Pascalize(ov.Name);
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"    public const string {prop} = \"pointer-{ov.Name}\";");
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"    public const string {prop}Exit = \"pointer-exit-{ov.Name}\";");
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"    public const string {prop}HintUi = \"pointer-hint-ui-{ov.Name}\";");
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"    public const string {prop}HintGrid = \"pointer-hint-grid-{ov.Name}\";");
            }
        }

        sb.AppendLine();
        sb.AppendLine("    // WM-mode layers (CAP single-tap state per context).");
        sb.AppendLine("    public const string Wm = \"wm\";");
        foreach (var ov in k.Overlays)
        {
            var prop = "Wm" + Pascalize(ov.Name);
            sb.AppendLine(CultureInfo.InvariantCulture, $"    public const string {prop} = \"wm-{ov.Name}\";");
        }

        sb.AppendLine();
        sb.AppendLine("    // WM-toggle layers (sticky/locked state per context).");
        sb.AppendLine("    public const string WmToggle = \"wm-toggle\";");
        foreach (var ov in k.Overlays)
        {
            var prop = "Wm" + Pascalize(ov.Name) + "Toggle";
            sb.AppendLine(CultureInfo.InvariantCulture, $"    public const string {prop} = \"wm-{ov.Name}-toggle\";");
        }

        sb.AppendLine();
        sb.AppendLine("    // Sub-mode layers (one-shot + toggle variants).");
        foreach (var sm in k.SubModes)
        {
            var pascal = Pascalize(sm.Name);
            sb.AppendLine(CultureInfo.InvariantCulture, $"    public const string Wm{pascal} = \"wm-{sm.Name}\";");
            sb.AppendLine(CultureInfo.InvariantCulture, $"    public const string Wm{pascal}Toggle = \"wm-{sm.Name}-toggle\";");
        }

        if (k.VirtualKeys.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    // Virtual keys the bridge taps over TCP with ActOnFakeKey.");
            foreach (var vk in k.VirtualKeys)
            {
                var pascal = string.Concat(
                    vk.Name.Split('-').Select(Pascalize));
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"    public const string VirtualKey{pascal} = \"{vk.Name}\";");
            }
        }

        if (k.PointerMode is not null)
        {
            sb.AppendLine();
            sb.AppendLine("    public static string PointerForBase(string baseLayer) => baseLayer switch");
            sb.AppendLine("    {");
            foreach (var ov in k.Overlays)
            {
                var pascal = Pascalize(ov.Name);
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"        Base{pascal} => Pointer{pascal},");
            }
            sb.AppendLine("        _ => Pointer,");
            sb.AppendLine("    };");
            sb.AppendLine();
            sb.AppendLine("    public static bool IsPointerLayer(string layerName) => layerName switch");
            sb.AppendLine("    {");
            sb.AppendLine("        Pointer => true,");
            foreach (var ov in k.Overlays)
            {
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"        Pointer{Pascalize(ov.Name)} => true,");
            }
            sb.AppendLine("        _ => false,");
            sb.AppendLine("    };");
            sb.AppendLine();
            sb.AppendLine("    public static bool IsPointerExitLayer(string layerName) => layerName switch");
            sb.AppendLine("    {");
            sb.AppendLine("        PointerExit => true,");
            foreach (var ov in k.Overlays)
            {
                sb.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"        Pointer{Pascalize(ov.Name)}Exit => true,");
            }
            sb.AppendLine("        _ => false,");
            sb.AppendLine("    };");
            sb.AppendLine();
            EmitPointerLayerPredicate(
                sb,
                "IsPointerUiHintLayer",
                "PointerHintUi",
                k.Overlays,
                "HintUi");
            sb.AppendLine();
            EmitPointerLayerPredicate(
                sb,
                "IsPointerGridHintLayer",
                "PointerHintGrid",
                k.Overlays,
                "HintGrid");
            sb.AppendLine();
            sb.AppendLine("    public static bool IsPointerDepartureLayer(string layerName) =>");
            sb.AppendLine("        IsPointerExitLayer(layerName)");
            sb.AppendLine("        || IsPointerUiHintLayer(layerName)");
            sb.AppendLine("        || IsPointerGridHintLayer(layerName);");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitPointerLayerPredicate(
        StringBuilder sb,
        string methodName,
        string defaultLayer,
        IReadOnlyList<Overlay> overlays,
        string propertySuffix)
    {
        sb.AppendLine(
            CultureInfo.InvariantCulture,
            $"    public static bool {methodName}(string layerName) => layerName switch");
        sb.AppendLine("    {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"        {defaultLayer} => true,");
        foreach (var ov in overlays)
        {
            sb.AppendLine(
                CultureInfo.InvariantCulture,
                $"        Pointer{Pascalize(ov.Name)}{propertySuffix} => true,");
        }
        sb.AppendLine("        _ => false,");
        sb.AppendLine("    };");
    }

    private static string Pascalize(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        return char.ToUpperInvariant(s[0]) + s[1..];
    }
}
